name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BasePublicPath: ${{ secrets.BASE_PUBLIC_PATH }}

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.9.5
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "pnpm"

      - run: pnpm i -g @antfu/ni
      - run: |
          nci
          nr lint
          nr test --run
          nr build
          cp dist/index.html dist/404.html

      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
